export const START_LOADING= 'START_LOADING'
export const END_LOADING= 'END_LOADING'

export const GET_MEMBERS= 'GET_MEMBERS'
export const GET_FACULTY= 'GET_FACULTY'
export const GET_ALUMNI= 'GET_ALUMNI'
export const GET_DEVELOPERS= 'GET_DEVELOPERS'
export const GET_EVENTS= 'POST_EVENTS'

export const POST_MEMBERS= 'POST_MEMBERS'
export const POST_FACULTY= 'POST_FACULTY'
export const POST_ALUMNI= 'POST_ALUMNI'
export const POST_DEVELOPERS= 'POST_DEVELOPERS'
export const POST_EVENTS= 'POST_EVENTS'

export const GET_UPCOMING= 'GET_UPCOMING';
export const GET_SOCIETY_DATA='GET_SOCIETY_DATA';

export const LOGIN= 'LOGIN'